### ISSUE TITLE
Impossible to Check into train/select Destination 

### ISSUE THREAD

**Issue by ChillLP** [Traewelling/traewelling#2680] opened 2024-06-11 12:47 UTC
### Describe the bug

At around 14:30 i attempted to Check into the ICE 724 from cologne messe/ Deutz to Düsseldorf. I was able to select the train, but Not able to select a Destination, as it didnt load. I tried IT via träwelldroid at First and then via träwellings Website, which didnt Work, either.
Other Trains i was able to select without issue.

### Steps to reproduce

See described above. - i will Provide a Video as soon as its uploaded.

### Browser

Opera (chomium) and Träwelldroid (via API)

**Comment by ChillLP** [comment] 2024-06-11 12:48
https://youtu.be/MLsvFLNSZLs?si=lGjOzasPdUBPCRgC

**Comment by marhei** [comment] 2024-06-11 13:12
Duplicate of #2674.

**Comment by ChillLP** [comment] 2024-06-11 13:15
Interesting...

**Comment by MrKrisKrisu** [comment] 2024-06-11 13:32
HAFAS is returning a HTTP 502 here.

```
{
    "isHafasError": true,
    "request": "{\"lang\":\"en\",\"svcReqL\":[{\"cfg\":{\"polyEnc\":\"GPA\",\"rtMode\":\"HYBRID\"},\"meth\":\"JourneyDetails\",\"req\":{\"jid\":\"2|#VN#1#ST#1717614449#PI#0#ZI#2117087#TA#0#DA#110624#1S#8000261#1T#847#LS#8000085#LT#1351#PU#80#RT#3#CA#ICE#ZE#724#ZB#ICE++724#PC#0#FR#8000261#FT#847#TO#8000085#TT#1351#\",\"name\":\"ICE 724\",\"getPolyline\":true}}],\"client\":{\"type\":\"AND\",\"id\":\"DB\",\"v\":21120000,\"name\":\"DB Navigator\"},\"ext\":\"DB.R21.12.a\",\"ver\":\"1.34\",\"auth\":{\"type\":\"AID\",\"aid\":\"n91dB8Z77MLdoR0K\"}}",
    "url": "https://reiseauskunft.bahn.de/bin/mgate.exe?checksum=706c34a76ce640511f6328d0c72ec6eb",
    "statusCode": 200,
    "code": "PARAMETER",
    "message": "HCI Service: parameter invalid",
    "responseId": "yd4g4he82smpw48g",
    "error": true,
    "msg": "HAFAS error: HCI Service: parameter invalid"
}
```

**Comment by MrKrisKrisu** [comment] 2024-06-11 13:33
This belongs to #2672.

**Comment by MrKrisKrisu** [comment] 2024-06-11 14:35
Unfortunately, there is nothing we can do here. We (@HerrLevin  and I) have just tested everything possible.

It is not Träwelling's fault.

It is not [DB-Rest](https://github.com/derhuerst/db-rest)'s fault.

It is not the [hafas-client](https://github.com/public-transport/hafas-client)'s fault.

It is a HAFAS error - but only on some journeys.

**Closed as completed by MrKrisKrisu** 2024-06-11 14:35 UTC
Labels: 🕰️ timetable issues

**Comment by MrKrisKrisu** [comment] 2024-06-11 15:20
> It is not Träwelling's fault.

It was Träwelling's fault.
https://github.com/Traewelling/traewelling/pull/2681

**Comment by HerrLevin** [comment] 2024-06-11 15:22
Further investigation found that I'm responsible. It should all work now. (See #2681)

**Comment by HerrLevin** [comment] 2024-06-11 15:23
> > It is not Träwelling's fault.
> 
> It was Träwelling's fault. #2681

Oh, you were faster. :D

**Comment by ChillLP** [comment] 2024-06-12 08:50
Thank you for the quick fix!
