### ISSUE TITLE
Notification count requests get sent twice simultaneously

### ISSUE THREAD

**Issue by d3d9** [Traewelling/traewelling#2193] opened 2023-12-09 23:35 UTC
### Describe the bug

![Screenshot of the network inspect view of a browser, there are always two count requests simultaneously](https://github.com/Traewelling/traewelling/assets/9254305/2e4e3662-87dd-4c6c-9d29-abb701e18b96)

### Steps to reproduce

Open the Träwelling website when logged in, check out the requests over time

### Browser

Edge, Firefox

**Comment by MrKrisKrisu** [comment] 2023-12-11 23:02
That's because ```<notification-bell>``` is mounted twice. I don't know how to fix this `vue` issue - @HerrLevin do you have an idea?

![image](https://github.com/Traewelling/traewelling/assets/4103693/86900fc4-e894-491f-a7ac-634bfb5c9873)

![image](https://github.com/Traewelling/traewelling/assets/4103693/2767faf8-1872-44f0-b4e8-a822c9988eeb)

**Comment by HerrLevin** [comment] 2023-12-12 09:47
This is currently the intended behaviour since the navbar is still implemented in blade and not in vue itself. It's not nice but we have to start somewhere. This will be fixed over time but currently the simultaneous request is a "feature" and not a bug

**Closed as not planned** 2023-12-12 09:47 UTC

**Comment by HerrLevin** [comment] 2023-12-12 09:49
@MrKrisKrisu this can be fixed when #2177 is merged. 👀

**Comment by MrKrisKrisu** [comment] 2023-12-12 11:04
> @MrKrisKrisu this can be fixed when #2177 is merged. 👀

feel free to merge. 👀
