### ISSUE TITLE
API v1 returns 200 on invalid auth

### ISSUE THREAD

**Issue by jheubuch** [Traewelling/traewelling#1175] opened 2022-11-11 07:43 UTC
**Describe the bug**
When a protected endpoint is called and no/a in valid token is sent within the Authorization header, the API returns an HTTP status code `200` with the Träwelling login page in the body.

**To Reproduce**

1. Log in via API
2. Store the Bearer token
3. Do a protected request with the bearer token -> get data
4. Invalidate token via Träwelling website
5. Do a protected request with the invalidated bearer token -> get `200` with login page

**Expected behavior**
I expect the API to send a `401 Unauthorized` so that API clients can handle invalid credentials.

**Comment by MrKrisKrisu** [comment] 2022-11-19 13:41
I can reproduce this, but I can't find a cause at the moment. This is in the middleware "auth:api". But this is from Laravel Passport.

**Comment by MrKrisKrisu** [comment] 2022-11-19 13:47
@HerrLevin help?

**Comment by HerrLevin** [comment] 2022-11-19 19:04
Okay so this is actually Laravel's intended behavior. It requires a `'accept: application/json'`-header, otherwise the internal redirect-mechanisms will be called. (in this example the redirect to the login page)

I don't see this as a bug since it's Laravel's intended behavior (I'm not saying that I like their way of doing it), hence I'm closing this ticket. I'll still try to implement a workaround in #1186. If I'm not successful in a "low cost"-manner, we'll sadly keep this behavior.

**Closed as completed by HerrLevin** 2022-11-19 19:04 UTC
Labels: 🙏 help wanted, ✔️ verified
