### ISSUE TITLE
Exporting data not possible

### ISSUE THREAD

**Issue by dasBunny** [Traewelling/traewelling#586] opened 2021-10-27 21:40 UTC
**Describe the bug**
On the export data page, clicking on the 'Export as pdf' button will redirect to a 500 server error page. Selecting .csv or .json format in the dropdown menu does not work either, as clicking the arrow button does not do anything.
This feature did previously work, but since about 1-2 weeks I cannot export my data anymore. 

**To Reproduce**

1. Go to export data page
2. Click on export as .pdf
3. See error

**Expected behavior**
When clicking on export as pdf, a pdf download should start. When clicking on the arrow for the drop down menu, selection of .csv and .json should be possible

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Tried on firefox and chrome

**Comment by MrKrisKrisu** [comment] 2021-10-30 12:30
I cannot reproduce the 500 error. However, there is a general problem with the export, which will be fixed in PR #588, #589, #590 and #591.

If you get a 500 error I would appreciate the date and time of the request so I can look in the error log.

**Comment by MrKrisKrisu** [comment] 2021-10-30 12:39
Nevermind, found it. That was my mistake, sorry for that! It will be fixed in the next rollout.

**Closed as completed** 2021-10-30 20:32 UTC
