### ISSUE TITLE
API: Wrong response of `DELETE /status/{id}`

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#2063] opened 2023-10-16 20:25 UTC
### Discussed in https://github.com/Traewelling/traewelling/discussions/2060

<div type='discussions-op-text'>

<sup>Originally posted by **marhei** October  8, 2023</sup>
Instead of a status element `success`, as specified in the docs, you get back a message element with a localised message in it</div>

**Comment by HerrLevin** [comment] 2024-02-10 20:33
Duplicate of #1969

**Closed as completed by HerrLevin** 2024-02-10 20:33 UTC
Labels: 🔌 API
