### ISSUE TITLE
Points and Tags

### ISSUE THREAD

**Issue by Blackscreen21** [Traewelling/traewelling#2737] opened 2024-07-06 11:15 UTC
### Describe the bug

The screen which displays the route and the points for it is not showing after check-in. Meaning the user cannot see how many points they received.
Also the tags do not show in either the dashboard nor the profile, so they are pretty useless as of now.

### Steps to reproduce

Check-in with tags.
No overview screen.
Tags dissapear.

### Browser

Chrome

**Comment by pascalwittler** [comment] 2024-07-06 22:12
Tags currently only appear after clicking on the status itself – possible overlap with #2655

**Comment by pascalwittler** [comment] 2024-07-06 22:16
Although, I can confirm the first part (no more points, no more kilometers, and no more other people who checked in in the green success message box) since the new check-in dialog was released.

**Comment by MrKrisKrisu** [comment] 2024-07-07 10:35
> so they are pretty useless as of now.

I would like to deny that they are useless. They are simply not displayed excessively in the UI, but are present in the export and are a very powerful feature for statistics and co.

**Comment by MrKrisKrisu** [comment] 2024-07-07 10:36
Also, this is not a bug (so I'll close this for now) - can you please open a discussion for this or join in at #2655 if it fits there? Thank you!

https://github.com/Traewelling/traewelling/discussions/new?category=ideas-feature-requests

**Closed as not planned by MrKrisKrisu** 2024-07-07 10:36 UTC
