### ISSUE TITLE
Export not working with Firefox Preview (Mobile)

### ISSUE THREAD

**Issue by tobimori** [Traewelling/traewelling#87] opened 2020-08-24 12:30 UTC
**Describe the bug**
Trying to export the data of any timespan fails and results in a download of the html source, but with the file name and extension of the expected result.

**To Reproduce**
Use the Export function in Firefox Preview Mobile

**Expected behavior**
Exported data as in any other browser

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Browser: Firefox Nightly for Developers
 - Version: 200706 06:01

**Comment by jeyemwey** [comment] 2020-08-31 07:16
Hi Tobi,

thanks for the report. This is likely a bug in a Firefox Nightly version. I was able to reproduce the issue on Aug 25, but not with version `Nightly 20200830 06:01`. I would like to close this issue since no major browser seems to be impacted, but only some versions of the nightly build. If the issue occurs on future versions, please feel free to re-open this issue.

**Closed as completed by jeyemwey** 2020-08-31 07:16 UTC
