### ISSUE TITLE
Adding journey manually, that are not in the DB

### ISSUE THREAD

**Issue by someone649** [Traewelling/traewelling#1993] opened 2023-10-16 16:02 UTC
**Is your feature request related to a problem? Please describe.**
Not a Problem, but a feature request.

**Describe the solution you'd like**
Adding journeys manually, that are not in the timetable database. To prevent abuse of the point system, no points would be given, when manually adding a journey. Advantage is, that the statistics, that can be exported, will contain manually added journeys, probably with a remark (e.g. "manually added"), so that these journeys can be filtered.

**Describe alternatives you've considered**
None comes to my mind

**Additional context**
N/A

**Comment by ChillLP** [comment] 2023-10-16 16:27
There have been multiple issues For that already

**Comment by jheubuch** [comment] 2023-10-16 16:28
duplicate of #1518 or #1431 ?

**Closed as not planned** 2023-10-16 16:39 UTC
Labels: 🔁 duplicate
