### ISSUE TITLE
Notification Test fails all the time

### ISSUE THREAD

**Issue by jeyemwey** [Traewelling/traewelling#1911] opened 2023-09-17 12:25 UTC
The `Tests\Feature\APIv1\NotificationsTest::testApiEndpointCanMarkAllNotificationAsRead` flaps quite often. Whoever picks up the issue should check if there is some hidden concurrency in here.

**Comment by HerrLevin** [comment] 2023-09-23 16:50
Duplicate of #1833

**Closed as completed by HerrLevin** 2023-09-23 16:50 UTC
Labels: ✅ tests
