### ISSUE TITLE
"En Route" lagging and not loading

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1342] opened 2023-01-30 12:50 UTC
**Describe the bug**
"En Route" is not optimized, lagging, takes long to load or doesn't load and breaking the Browser

**To Reproduce**

1. Go to 'En Route'

**Expected behavior**
The Page should be loaded faster.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Firefox
- Version Newest

**Comment by jeyemwey** [comment] 2023-01-30 13:32
Thanks for the feedback. This looks like a duplicate of #1113, so I'd like to merge the two together.

**Closed as not planned** 2023-01-30 13:32 UTC
Labels: 🔁 duplicate
