### ISSUE TITLE
Not symmetrical status footer elements 

### ISSUE THREAD

**Issue by Oxbowatos** [Traewelling/traewelling#1506] opened 2023-03-26 10:25 UTC
**Describe the bug**
Today I saw that the Name and the Departure time are too close to the top and not vertically centered. 
Moreover, the Block User button does not align perfectly with the other choices. 

**To Reproduce**

1. Go to 'Dashboard'
2. See first Error
3. click on the Status Dropdown
4. See the second Error

**Expected behavior**
Better Frontend implementation and Design is required. 

**Screenshots**
![image](https://user-images.githubusercontent.com/123954576/227769480-f23d1fd1-fa14-499d-8f1e-34ad837ff661.png)
It is evident that the alignment is not symmetrical. 

![image](https://user-images.githubusercontent.com/123954576/227769531-1726e4f1-11b6-4ea6-8254-c47c6585e723.png)
Here you see it too.

**Desktop (please complete the following information):**

Any Os any Browser, tested with Firefox

**Comment by SoraCent** [comment] 2023-03-26 10:33
Me and my Friend (Which both making Webdesign) noticed that too yesterday evening 😂

**Comment by vainamov** [comment] 2023-03-26 11:09
The footer alignment will be fixed by #1505 and the icon alignment in the dropdown was already fixed in #1500 but reverted because of an issue with the event handler.

**Comment by jeyemwey** [comment] 2023-03-26 18:41
> but reverted because of an issue with the event handler

that issue no longer exists

**Closed as completed** 2023-03-26 20:05 UTC

**Comment by SoraCent** [comment] 2023-04-01 05:38
I know that the issue creator is blocked from the repo...

But I can confirm that it still happens for me on Firefox. The Icons at the Drop down aren't symmetrical and the text with the username and time is not vertically aligned.

**Comment by jeyemwey** [comment] 2023-04-01 06:06
Der Fehler wurde im Code behoben und wird mit der nächsten Version ausgerollt. Aus Entwicklungsseite ist keine Arbeit mehr notwendig. No need to panic.
