### ISSUE TITLE
Message funciton with other user?

### ISSUE THREAD

**Issue by Twinny446** [Traewelling/traewelling#1541] opened 2023-04-20 14:52 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MrKrisKrisu** [comment] 2023-04-20 14:54
Hello, please fill out the form correctly for future issues.

Also this feature request is a duplicate of #1356.

**Closed as not planned by MrKrisKrisu** 2023-04-20 14:54 UTC
