### ISSUE TITLE
Mastodon instance not working.

### ISSUE THREAD

**Issue by lomenzel** [Traewelling/traewelling#1955] opened 2023-10-03 13:16 UTC
**Describe the bug**
When trying to log in with Mastodon using the instance social.linux.pizza the page just reloads

**To Reproduce**

**Expected behavior**
Open the instances website

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Pixel 7 Pro
- OS: Android 13
- Browser chrome

**Comment by MrKrisKrisu** [comment] 2023-10-04 15:15
I can not verify on the PC with Chrome. There it works.

On my Pixel 6 Pro with Chrome, the page actually just reloads. (on enter and on button click)

**Comment by NyCodeGHG** [comment] 2023-10-04 16:14
Can't reproduce on Pixel 5 on Firefox as well as Chrome.
Mastodon Login works fine for me

Chrome 117.0
Firefox 118.0

This sounds like a very interesting bug 😵‍💫

**Comment by lomenzel** [comment] 2023-10-04 16:52
Yes, for me it only happens with social.linux.pizza, other instances are working fine

**Comment by NyCodeGHG** [comment] 2023-10-04 17:33
Oh i see, trying social.linux.pizza results in an infinite redirect

**Comment by HerrLevin** [comment] 2023-10-06 10:57
Okay this is really weird. Social.linux.pizza results in an instant redirect on my iPhone but not on my mac.

This sounds like a problem with this specific instance and not with traewelling, but I'll try to debug a bit.

**Comment by lomenzel** [comment] 2023-11-23 08:02
I just tried it again and it suddenly worked.

**Comment by rugk** [comment] 2023-11-28 01:10
I am sorry, but I am failing to see how https://social.linux.pizza/ is related to Traewelling? The instance is not even related to trains, apparently.

I am wholly totally confused by this issue… (also by the fact is has been validated and confirmed etc.)

**Comment by rugk** [comment] 2023-11-28 01:11
Oh I am stupid, you mean the login with _that_ instance is broken, now I get it sorry. :see_no_evil:

**Comment by MrKrisKrisu** [comment] 2023-11-28 06:40
> I just tried it again and it suddenly worked.

Well, for me too on my smartphone. The case mentioned from me above is solved magically. 🪄

So I will close this issue - feel free to write if this happens again. 🥴

**Closed as not planned by MrKrisKrisu** 2023-11-28 06:40 UTC
Labels: 🎨 ui, ✔️ verified
